"""update_tabel

Revision ID: d64c37f71555
Revises: 7c139683ccb2
Create Date: 2025-12-17 23:48:06.411342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd64c37f71555'
down_revision: Union[str, Sequence[str], None] = '7c139683ccb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=False))
    op.drop_column('user', 'hash_pass')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hash_pass', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
